version: '3.8'

services:
  appwrite:
    image: appwrite/appwrite:1.7.0
    depends_on:
      - mariadb
      - redis
    environment:
      _APP_ENV: production
      _APP_OPENSSL_KEY_V1: ae817035ed941ac07a11e3a6a7d7493b7fc5bc93df429610baee44b037079959
      _APP_DOMAIN: 173.212.225.43
      _APP_DOMAIN_TARGET: 173.212.225.43
      _APP_DB_HOST: mariadb
      _APP_DB_PORT: 3306
      _APP_DB_SCHEMA: appwrite
      _APP_DB_USER: root
      _APP_DB_PASS: Mir0rj8#i9
      _APP_REDIS_HOST: redis
      _APP_REDIS_PORT: 6379
    volumes:
      - appwrite-data:/storage
    restart: always

  mariadb:
    image: mariadb:10.7
    environment:
      MYSQL_ROOT_PASSWORD: Mir0rj8#i9
      MYSQL_DATABASE: appwrite
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always

  redis:
    image: redis:7
    volumes:
      - redis-data:/data
    restart: always

volumes:
  appwrite-data:
  mariadb-data:
  redis-data:
